/*
 * Domain Graph API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pat.cataldo@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Node} from './Node';
import {Relationship} from './Relationship';

/**
 * The Graph model module.
 * @module model/Graph
 * @version 1.0.0
 */
export class Graph {
  /**
   * Constructs a new <code>Graph</code>.
   * @alias module:model/Graph
   * @class
   * @param nodes {Array.<module:model/Node>} 
   * @param relationships {Array.<module:model/Relationship>} 
   */
  constructor(nodes, relationships) {
    this.nodes = nodes;
    this.relationships = relationships;
  }

  /**
   * Constructs a <code>Graph</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Graph} obj Optional instance to populate.
   * @return {module:model/Graph} The populated <code>Graph</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Graph();
      if (data.hasOwnProperty('nodes'))
        obj.nodes = ApiClient.convertToType(data['nodes'], [Node]);
      if (data.hasOwnProperty('relationships'))
        obj.relationships = ApiClient.convertToType(data['relationships'], [Relationship]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Node>} nodes
 */
Graph.prototype.nodes = undefined;

/**
 * @member {Array.<module:model/Relationship>} relationships
 */
Graph.prototype.relationships = undefined;


