/*
 * Domain Graph API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pat.cataldo@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Property} from './Property';
import {Relationship} from './Relationship';

/**
 * The Node model module.
 * @module model/Node
 * @version 1.0.0
 */
export class Node {
  /**
   * Constructs a new <code>Node</code>.
   * @alias module:model/Node
   * @class
   * @param type {String} 
   */
  constructor(type) {
    this.type = type;
  }

  /**
   * Constructs a <code>Node</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Node} obj Optional instance to populate.
   * @return {module:model/Node} The populated <code>Node</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Node();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('properties'))
        obj.properties = ApiClient.convertToType(data['properties'], [Property]);
      if (data.hasOwnProperty('relationships'))
        obj.relationships = ApiClient.convertToType(data['relationships'], [Relationship]);
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
Node.prototype.type = undefined;

/**
 * @member {Array.<module:model/Property>} properties
 */
Node.prototype.properties = undefined;

/**
 * @member {Array.<module:model/Relationship>} relationships
 */
Node.prototype.relationships = undefined;


