/*
 * Domain Graph API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pat.cataldo@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The Property model module.
 * @module model/Property
 * @version 1.0.0
 */
export class Property {
  /**
   * Constructs a new <code>Property</code>.
   * @alias module:model/Property
   * @class
   * @param name {String} 
   * @param value {String} 
   */
  constructor(name, value) {
    this.name = name;
    this.value = value;
  }

  /**
   * Constructs a <code>Property</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Property} obj Optional instance to populate.
   * @return {module:model/Property} The populated <code>Property</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Property();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Property.prototype.name = undefined;

/**
 * @member {String} value
 */
Property.prototype.value = undefined;


