/*
 * Domain Graph API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pat.cataldo@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The RelationshipTemplate model module.
 * @module model/RelationshipTemplate
 * @version 1.0.0
 */
export class RelationshipTemplate {
  /**
   * Constructs a new <code>RelationshipTemplate</code>.
   * @alias module:model/RelationshipTemplate
   * @class
   * @param label {String} 
   * @param text {String} 
   */
  constructor(label, text) {
    this.label = label;
    this.text = text;
  }

  /**
   * Constructs a <code>RelationshipTemplate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RelationshipTemplate} obj Optional instance to populate.
   * @return {module:model/RelationshipTemplate} The populated <code>RelationshipTemplate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RelationshipTemplate();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} label
 */
RelationshipTemplate.prototype.label = undefined;

/**
 * @member {String} text
 */
RelationshipTemplate.prototype.text = undefined;


