/*
 * Domain Graph API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pat.cataldo@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient";
import {Graph} from '../model/Graph';

/**
* Graph service.
* @module api/GraphApi
* @version 1.0.0
*/
export class GraphApi {

    /**
    * Constructs a new GraphApi. 
    * @alias module:api/GraphApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * gets the full graph
     * Returns the full graph for the Domain Graph Visualizer Application 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Graph} and HTTP response
     */
    getGraphWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Graph;

      return this.apiClient.callApi(
        '/graph', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * gets the full graph
     * Returns the full graph for the Domain Graph Visualizer Application 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Graph}
     */
    getGraph() {
      return this.getGraphWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
