/*
 * Domain Graph API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pat.cataldo@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from "../ApiClient";
import {Relationship} from '../model/Relationship';

/**
* Relationships service.
* @module api/RelationshipsApi
* @version 1.0.0
*/
export class RelationshipsApi {

    /**
    * Constructs a new RelationshipsApi. 
    * @alias module:api/RelationshipsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * @param {Number} relId the id of the relationship
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteRelationshipByIdWithHttpInfo(relId) {
      let postBody = null;

      // verify the required parameter 'relId' is set
      if (relId === undefined || relId === null) {
        throw new Error("Missing the required parameter 'relId' when calling deleteRelationshipById");
      }


      let pathParams = {
        'relId': relId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/relationships/{relId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} relId the id of the relationship
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteRelationshipById(relId) {
      return this.deleteRelationshipByIdWithHttpInfo(relId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * @param {Number} relId the id of the relationship
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Relationship} and HTTP response
     */
    getRelationshipByIdWithHttpInfo(relId) {
      let postBody = null;

      // verify the required parameter 'relId' is set
      if (relId === undefined || relId === null) {
        throw new Error("Missing the required parameter 'relId' when calling getRelationshipById");
      }


      let pathParams = {
        'relId': relId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = Relationship;

      return this.apiClient.callApi(
        '/relationships/{relId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * @param {Number} relId the id of the relationship
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Relationship}
     */
    getRelationshipById(relId) {
      return this.getRelationshipByIdWithHttpInfo(relId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
