/*
 * Domain Graph API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pat.cataldo@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DomainGraphClient);
  }
}(this, function(expect, DomainGraphClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Configuration', function() {
      beforeEach(function() {
        instance = new DomainGraphClient.Configuration();
      });

      it('should create an instance of Configuration', function() {
        // TODO: update the code to test Configuration
        expect(instance).to.be.a(DomainGraphClient.Configuration);
      });

      it('should have the property nodeLabels (base name: "nodeLabels")', function() {
        // TODO: update the code to test the property nodeLabels
        expect(instance).to.have.property('nodeLabels');
        // expect(instance.nodeLabels).to.be(expectedValueLiteral);
      });

      it('should have the property relationshipLabels (base name: "relationshipLabels")', function() {
        // TODO: update the code to test the property relationshipLabels
        expect(instance).to.have.property('relationshipLabels');
        // expect(instance.relationshipLabels).to.be(expectedValueLiteral);
      });

    });
  });

}));
